# Generated by Django 4.0.3 on 2022-04-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webservice', '0003_alter_city_options_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webservice.city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='street_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webservice.street'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webservice.city'),
        ),
    ]
