# Generated by Django 4.0.3 on 2022-04-10 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('city_id', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webservice.city')),
                ('street_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webservice.street')),
            ],
        ),
    ]
